import { ICompanyUpdatePayload } from "common/models/company.model";

export const COMPANY_CREATE_DEFAULTS: ICompanyUpdatePayload = {
    nipc: "",
    fiscal_name: "",
    slug: null,
    trade_name: null,
    responsible_name: null,
    address: null,
    postal_code: null,
    district_id: null,
    municipality_id: null,
    parish_id: null,
    phone: null,
    mobile: null,
    email: null,
    invoice_email: null,
    registry_office: null,
    registry_office_number: null,
    capital_social: null,
    nib: null,
    registration_fees: 0,
    export_promotion_price: 0,
    credit_intermediation_link: null,
    vat_value: null,
    facebook_page_id: null,
    facebook_pixel_id: null,
    facebook_access_token: null,
    website: null,
    instagram: null,
    youtube: null,
    facebook: null,
    google: null,
    lead_hours_pending: null,
    lead_distribution: "manual",
    ad_text: null,
    pdf_path: null,
    logo_path: null,
    banner_path: null,
    carmine_logo_path: null,
    plan_id: 1,
};