services:

  webserver:
    image: nginx:latest
    container_name: xplendor-nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx/load/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./server:/var/www/html:delegated
      - xplendor_vendor:/var/www/html/vendor
    depends_on:
      - php
    networks:
      - xplendor

  db:
    image: mariadb:10.6.11-focal
    container_name: xplendor-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: xplendor
      MYSQL_USER: xplendor
      MYSQL_PASSWORD: xplendor
    volumes:
      - db_data_xplendor:/var/lib/mysql
    ports:
      - "3309:3306"
    restart: always
    networks:
      - xplendor

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: xplendor-phpadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    restart: always
    depends_on:
      - db
    networks:
      - xplendor

  php:
    build:
      context: ./docker/php
    container_name: xplendor-php
    restart: always
    working_dir: /var/www/html
    expose:
      - "9000"
    environment:
      PHP_IDE_CONFIG: "serverName=xplendorDevServer"
      COMPOSER_CACHE_DIR: /tmp/composer
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./server:/var/www/html:delegated
      - xplendor_vendor:/var/www/html/vendor
      - xplendor_composer_cache:/tmp/composer
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini:ro
      - ./docker/php/conf.d/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini:ro
    depends_on:
      - db
      - redis
    networks:
      - xplendor

  redis:
    image: redis:alpine
    container_name: xplendor-redis
    restart: always
    volumes:
      - ./docker/redis/db:/data
    ports:
      - "6381:6379"
    networks:
      - xplendor

networks:
  xplendor: {}

volumes:
  db_data_xplendor:
  xplendor_vendor:
  xplendor_composer_cache:
