server {
    listen 80;
    server_name _;

    # uploads grandes
    client_max_body_size 700M;

    # -------------------------
    # FRONTEND (React build)
    # -------------------------
    root /var/www/web/build;
    index index.html;

    location / {
        try_files $uri /index.html;
    }

    # -------------------------
    # STORAGE público (imagens)
    # -------------------------
    location ^~ /storage/ {
        # o Laravel public/storage aponta para storage/app/public
        # no container isto costuma existir em /var/www/html/public/storage
        alias /var/www/html/public/storage/;

        access_log off;
        expires 30d;
        add_header Cache-Control "public";
        try_files $uri =404;
    }

    # -------------------------
    # API (Laravel)
    # -------------------------
    location ^~ /api/ {
        # muda o root só para esta location
        root /var/www/html/public;
        try_files $uri /index.php?$query_string;
    }

    # PHP só para API
    location ~ ^/api/.*\.php$ {
        root /var/www/html/public;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_pass php:9000;
    }

    # Assets cacheáveis do frontend
    location ~* \.(css|js|jpg|jpeg|png|webp|gif|svg|ico|woff|woff2)$ {
        access_log off;
        expires 30d;
        add_header Cache-Control "public";
        try_files $uri =404;
    }
}