<?php

declare(strict_types=1);

namespace App\Access;

use Illuminate\Routing\Route;

/**
 * ACL: a permissão de CADA rota de empresa (/companies/{id}/… e /companies/{company}),
 * declarada num só sítio. A chave é "MÉTODO uri" sem o prefixo api/v1/companies/ (nos
 * PUT|PATCH, o PUT). A ação é a do que a rota faz, não a do verbo: por exemplo, um POST de
 * sincronização é "editar" e um POST de aprovação é "aprovar".
 *
 * O teste AccessCatalogTest falha se uma rota de empresa não estiver aqui (ou tiver uma
 * permissão que não existe no catálogo), e se aqui houver uma chave sem rota.
 */
final class RoutePermissions
{
    public const PREFIX = 'api/v1/companies/';

    public const MAP = [
        // ── empresa ──
        'GET {company}' => 'empresa.ver',
        'PUT {company}' => 'empresa.editar',
        'GET {id}/ai-requests/latest' => 'empresa.ver',
        'POST {id}/ai-requests/{requestId}/dismiss' => 'empresa.ver',
        'GET {id}/alerts' => 'empresa.ver',
        'PATCH {id}/alerts/read' => 'empresa.ver',
        'GET {id}/alerts/unread-count' => 'empresa.ver',
        'POST {id}/alerts/{alertId}/read' => 'empresa.ver',
        'GET {id}/dashboard/base' => 'empresa.ver',
        'DELETE {id}/management' => 'empresa.aprovar',
        'GET {id}/management' => 'empresa.ver',
        'POST {id}/management/connections' => 'empresa.aprovar',
        'GET {id}/management/requests' => 'empresa.aprovar',
        'POST {id}/management/requests/{requestId}/accept' => 'empresa.aprovar',
        'POST {id}/management/requests/{requestId}/decline' => 'empresa.aprovar',
        'GET {id}/my-modules' => 'empresa.ver',
        'GET {id}/my-access' => 'empresa.ver',
        // ── utilizadores ──
        'GET {id}/collaborators' => 'utilizadores.ver',
        'POST {id}/collaborators' => 'utilizadores.criar',
        'DELETE {id}/collaborators/{collaborator}' => 'utilizadores.apagar',
        'GET {id}/collaborators/{collaborator}' => 'utilizadores.ver',
        'PUT {id}/collaborators/{collaborator}' => 'utilizadores.editar',
        'POST {id}/collaborators/{collaborator}/access' => 'utilizadores.configurar',
        'DELETE {id}/collaborators/{collaborator}/access/invite' => 'utilizadores.configurar',
        'POST {id}/collaborators/{collaborator}/access/resend' => 'utilizadores.configurar',
        'POST {id}/collaborators/{collaborator}/access/restore' => 'utilizadores.configurar',
        'POST {id}/collaborators/{collaborator}/access/revoke' => 'utilizadores.configurar',
        'POST {id}/collaborators/{collaborator}/activate' => 'utilizadores.editar',
        'POST {id}/collaborators/{collaborator}/deactivate' => 'utilizadores.editar',
        'DELETE {id}/collaborators/{collaborator}/photo' => 'utilizadores.editar',
        'POST {id}/collaborators/{collaborator}/photo' => 'utilizadores.editar',
        'GET {id}/departments' => 'utilizadores.ver',
        'POST {id}/departments' => 'utilizadores.criar',
        'POST {id}/departments/suggested' => 'utilizadores.criar',
        'DELETE {id}/departments/{department}' => 'utilizadores.apagar',
        'PUT {id}/departments/{department}' => 'utilizadores.editar',
        'PUT {id}/editorial/approvers/{userId}' => 'utilizadores.configurar',
        'GET {id}/users' => 'utilizadores.ver',
        'POST {id}/users' => 'utilizadores.configurar',
        'GET {id}/users/{user}' => 'utilizadores.ver',
        'PUT {id}/users/{user}' => 'utilizadores.configurar',
        // ── integracoes ──
        'POST {id}/carmine-connection' => 'integracoes.configurar', // D7
        'DELETE {id}/carmine-connection/{carmine_connection}' => 'integracoes.configurar', // D7
        'GET {id}/carmine-connection/{carmine_connection}' => 'integracoes.ver',
        'PUT {id}/carmine-connection/{carmine_connection}' => 'integracoes.configurar', // D7
        'GET {id}/integrations' => 'integracoes.ver',
        'DELETE {id}/integrations/covermanager' => 'integracoes.configurar', // D7
        'GET {id}/integrations/covermanager' => 'integracoes.ver',
        'POST {id}/integrations/covermanager/connect' => 'integracoes.configurar', // D7
        'DELETE {id}/integrations/google' => 'integracoes.configurar', // D7
        'POST {id}/integrations/google/connect' => 'integracoes.configurar', // D7
        'GET {id}/integrations/history' => 'integracoes.ver',
        'DELETE {id}/integrations/meta' => 'integracoes.configurar',
        'PATCH {id}/integrations/meta/account' => 'integracoes.configurar',
        'GET {id}/integrations/meta/ad-accounts' => 'integracoes.configurar',
        'GET {id}/integrations/meta/adsets' => 'integracoes.ver',
        'POST {id}/integrations/meta/connect' => 'integracoes.configurar',
        'GET {id}/integrations/meta/oauth-url' => 'integracoes.configurar',
        'GET {id}/integrations/pingwin' => 'integracoes.ver',
        'POST {id}/integrations/pingwin/connect' => 'integracoes.configurar', // D7
        'DELETE {id}/integrations/social' => 'integracoes.configurar',
        'GET {id}/integrations/social' => 'integracoes.ver',
        'PUT {id}/integrations/social/accounts' => 'integracoes.configurar',
        'GET {id}/integrations/social/auth-url' => 'integracoes.configurar',
        'GET {id}/integrations/social/candidates' => 'integracoes.configurar',
        'GET {id}/setup-link' => 'integracoes.configurar',
        'POST {id}/setup-links' => 'integracoes.configurar',
        'POST {id}/setup-links/{linkId}/extend' => 'integracoes.configurar',
        'POST {id}/setup-links/{linkId}/revoke' => 'integracoes.configurar',
        // ── faturacao_xplendor ──
        'PATCH {id}/quotes/{quote}/decision' => 'faturacao_xplendor.aprovar',
        'POST {id}/support-tickets/quotes/approve' => 'faturacao_xplendor.aprovar',
        'PATCH {id}/support-tickets/{ticket}/quote-decision' => 'faturacao_xplendor.aprovar',
        'GET {id}/xplendor-charges' => 'faturacao_xplendor.ver',
        'GET {id}/xplendor-charges/{chargeId}/invoice' => 'faturacao_xplendor.ver',
        'POST {id}/xplendor-charges/{chargeId}/paid' => 'faturacao_xplendor.aprovar',
        // ── editorial ──
        'POST {id}/editorial/anchors' => 'editorial.editar',
        'POST {id}/editorial/anchors/{anchorId}/hide' => 'editorial.editar',
        'POST {id}/editorial/anchors/{anchorId}/show' => 'editorial.editar',
        'POST {id}/editorial/approvals/approve-all' => 'editorial.aprovar',
        'GET {id}/editorial/board' => 'editorial.ver',
        'GET {id}/editorial/calendar' => 'editorial.ver',
        'GET {id}/editorial/formats' => 'editorial.ver',
        'GET {id}/editorial/grid' => 'editorial.ver',
        'POST {id}/editorial/ideas' => 'editorial.criar',
        'GET {id}/editorial/ideas/{requestId}' => 'editorial.ver',
        'POST {id}/editorial/ideas/{requestId}/accept' => 'editorial.criar',
        'POST {id}/editorial/media/uploads' => 'editorial.criar',
        'GET {id}/editorial/media/uploads/{uploadId}' => 'editorial.ver',
        'POST {id}/editorial/media/uploads/{uploadId}/chunk' => 'editorial.criar',
        'GET {id}/editorial/media/{assetId}' => 'editorial.ver',
        'POST {id}/editorial/months/{year}/{month}/close' => 'editorial.editar',
        'POST {id}/editorial/months/{year}/{month}/open' => 'editorial.editar',
        'DELETE {id}/editorial/own-anchors/{ownAnchorId}' => 'editorial.editar',
        'POST {id}/editorial/posts' => 'editorial.criar',
        'DELETE {id}/editorial/posts/{postId}' => 'editorial.apagar',
        'PUT {id}/editorial/posts/{postId}' => 'editorial.editar',
        'POST {id}/editorial/posts/{postId}/approve' => 'editorial.aprovar',
        'POST {id}/editorial/posts/{postId}/caption-suggestions' => 'editorial.editar',
        'GET {id}/editorial/posts/{postId}/caption-suggestions/{suggestionId}' => 'editorial.ver',
        'POST {id}/editorial/posts/{postId}/comments' => 'editorial.editar',
        'PUT {id}/editorial/posts/{postId}/content' => 'editorial.editar',
        'GET {id}/editorial/posts/{postId}/creative' => 'editorial.ver',
        'PUT {id}/editorial/posts/{postId}/creative' => 'editorial.editar',
        'POST {id}/editorial/posts/{postId}/creative-suggestions' => 'editorial.editar',
        'GET {id}/editorial/posts/{postId}/creative-suggestions/{suggestionId}' => 'editorial.ver',
        'PUT {id}/editorial/posts/{postId}/media' => 'editorial.editar',
        'POST {id}/editorial/posts/{postId}/move' => 'editorial.editar',
        'POST {id}/editorial/posts/{postId}/published' => 'editorial.editar',
        'POST {id}/editorial/posts/{postId}/request-changes' => 'editorial.aprovar',
        'PUT {id}/editorial/posts/{postId}/results' => 'editorial.editar',
        'POST {id}/editorial/posts/{postId}/skip-network' => 'editorial.editar',
        'GET {id}/editorial/posts/{postId}/workflow' => 'editorial.ver',
        'GET {id}/editorial/results' => 'editorial.ver',
        'GET {id}/editorial/review-links' => 'editorial.ver',
        'POST {id}/editorial/review-links' => 'editorial.criar',
        'GET {id}/editorial/review-links/candidates' => 'editorial.ver',
        'PUT {id}/editorial/review-links/{linkId}' => 'editorial.editar',
        'POST {id}/editorial/review-links/{linkId}/extend' => 'editorial.editar',
        'GET {id}/editorial/review-links/{linkId}/preview' => 'editorial.ver',
        'POST {id}/editorial/review-links/{linkId}/revoke' => 'editorial.editar',
        'POST {id}/editorial/sector' => 'editorial.editar',
        'PUT {id}/editorial/sector' => 'editorial.editar',
        'GET {id}/editorial/sectors' => 'editorial.ver',
        'GET {id}/editorial/today' => 'editorial.ver',
        'GET {id}/editorial/workflow-settings' => 'editorial.ver',
        'PUT {id}/editorial/workflow-settings' => 'editorial.configurar',
        // ── blog ──
        'GET {id}/blog-ai/context' => 'blog.ver',
        'POST {id}/blog-ai/drafts' => 'blog.criar',
        'GET {id}/blog-ai/drafts/{draft}' => 'blog.ver',
        'GET {id}/blogs' => 'blog.ver',
        'POST {id}/blogs' => 'blog.criar',
        'POST {id}/blogs/build-rss-url' => 'blog.ver',
        'DELETE {id}/blogs/{blog}' => 'blog.apagar',
        'GET {id}/blogs/{blog}' => 'blog.ver',
        'PUT {id}/blogs/{blog}' => 'blog.editar',
        'POST {id}/blogs/{blog}/approve' => 'blog.aprovar',
        'POST {id}/blogs/{blog}/back-to-draft' => 'blog.aprovar',
        'DELETE {id}/blogs/{blog}/banner' => 'blog.editar',
        'POST {id}/blogs/{blog}/request-changes' => 'blog.aprovar',
        'POST {id}/blogs/{blog}/submit' => 'blog.editar',
        // ── marca ──
        'GET {id}/brand-profile' => 'marca.ver',
        'PUT {id}/brand-profile' => 'marca.editar',
        'POST {id}/brand-profile/suggestions' => 'marca.criar',
        'GET {id}/brand-profile/suggestions/{suggestionId}' => 'marca.ver',
        'GET {id}/followers' => 'marca.ver',
        'POST {id}/followers' => 'marca.editar',
        'GET {id}/subscribers' => 'marca.ver',
        // ── bussola ──
        'GET {id}/integrations/pingwin/signals' => 'bussola.ver',
        'POST {id}/integrations/pingwin/signals/exclude-item' => 'bussola.editar',
        'POST {id}/integrations/pingwin/signals/ignore' => 'bussola.editar',
        'POST {id}/integrations/pingwin/signals/post' => 'bussola.criar',
        'POST {id}/integrations/pingwin/signals/restore' => 'bussola.editar',
        'GET {id}/marketing/bussola' => 'bussola.ver',
        'POST {id}/marketing/bussola/caption' => 'bussola.criar',
        'GET {id}/marketing/bussola/caption/{requestId}' => 'bussola.ver',
        'POST {id}/marketing/bussola/post' => 'bussola.criar',
        // ── resultados ──
        'GET {id}/analytics/automotive/marketing' => 'resultados.ver',
        'GET {id}/analytics/ga4/traffic' => 'resultados.ver',
        'GET {id}/analytics/meta/ad-tag-warnings' => 'resultados.ver',
        'GET {id}/analytics/meta/overview' => 'resultados.ver',
        'GET {id}/analytics/restaurant/marketing' => 'resultados.ver',
        'GET {id}/recommendations' => 'resultados.ver',
        // ── financas ──
        'GET {id}/customers' => 'financas.ver',
        'POST {id}/customers' => 'financas.criar',
        'DELETE {id}/customers/{customer}' => 'financas.apagar',
        'GET {id}/customers/{customer}' => 'financas.ver',
        'PUT {id}/customers/{customer}' => 'financas.editar',
        'GET {id}/customers/{customer}/hub' => 'financas.ver',
        'GET {id}/expense-categories' => 'financas.ver',
        'POST {id}/expense-categories' => 'financas.criar',
        'POST {id}/expense-categories/import-suggested' => 'financas.criar',
        'GET {id}/expense-categories/suggested' => 'financas.ver',
        'DELETE {id}/expense-categories/{expense_category}' => 'financas.apagar',
        'GET {id}/expense-categories/{expense_category}' => 'financas.ver',
        'PUT {id}/expense-categories/{expense_category}' => 'financas.editar',
        'GET {id}/expenses' => 'financas.ver',
        'POST {id}/expenses' => 'financas.criar',
        'GET {id}/expenses/summary' => 'financas.ver',
        'DELETE {id}/expenses/{expense}' => 'financas.apagar',
        'GET {id}/expenses/{expense}' => 'financas.ver',
        'PUT {id}/expenses/{expense}' => 'financas.editar',
        'GET {id}/suppliers' => 'financas.ver',
        'POST {id}/suppliers' => 'financas.criar',
        'DELETE {id}/suppliers/{supplier}' => 'financas.apagar',
        'GET {id}/suppliers/{supplier}' => 'financas.ver',
        'PUT {id}/suppliers/{supplier}' => 'financas.editar',
        // ── restauracao ──
        'GET {id}/analytics/pingwin/calendar' => 'restauracao.ver',
        'GET {id}/analytics/pingwin/dashboard' => 'restauracao.ver',
        'GET {id}/analytics/pingwin/monthly-billing' => 'restauracao.ver',
        'GET {id}/integrations/covermanager/settings' => 'restauracao.ver',
        'PATCH {id}/integrations/covermanager/settings' => 'restauracao.editar',
        'POST {id}/integrations/covermanager/sync' => 'restauracao.editar',
        'POST {id}/integrations/pingwin/articles' => 'restauracao.criar',
        'GET {id}/integrations/pingwin/articles/creation/{creationId}' => 'restauracao.ver',
        'GET {id}/integrations/pingwin/articles/deletion/{creationId}' => 'restauracao.ver',
        'GET {id}/integrations/pingwin/articles/edition/{creationId}' => 'restauracao.ver',
        'GET {id}/integrations/pingwin/articles/form-lookups' => 'restauracao.ver',
        'GET {id}/integrations/pingwin/articles/read/{token}' => 'restauracao.ver',
        'DELETE {id}/integrations/pingwin/articles/{catalogItemId}' => 'restauracao.apagar',
        'PUT {id}/integrations/pingwin/articles/{catalogItemId}' => 'restauracao.editar',
        'GET {id}/integrations/pingwin/articles/{catalogItemId}/supplier-prices' => 'restauracao.ver',
        'GET {id}/integrations/pingwin/articles/{productId}' => 'restauracao.ver',
        'GET {id}/integrations/pingwin/catalog' => 'restauracao.ver',
        'POST {id}/integrations/pingwin/catalog/sync' => 'restauracao.editar',
        'GET {id}/integrations/pingwin/documents' => 'restauracao.ver',
        'POST {id}/integrations/pingwin/documents' => 'restauracao.criar',
        'POST {id}/integrations/pingwin/documents/sync' => 'restauracao.editar',
        'POST {id}/integrations/pingwin/documents/sync-rich' => 'restauracao.editar',
        'GET {id}/integrations/pingwin/documents/writes/{writeId}' => 'restauracao.ver',
        'DELETE {id}/integrations/pingwin/documents/{externalId}' => 'restauracao.apagar',
        'GET {id}/integrations/pingwin/documents/{externalId}' => 'restauracao.ver',
        'PUT {id}/integrations/pingwin/documents/{externalId}' => 'restauracao.editar',
        'POST {id}/integrations/pingwin/excluded-items/{itemId}/include' => 'restauracao.configurar',
        'GET {id}/integrations/pingwin/families' => 'restauracao.ver',
        'POST {id}/integrations/pingwin/families/sync' => 'restauracao.editar',
        'GET {id}/integrations/pingwin/family-categories' => 'restauracao.ver',
        'PUT {id}/integrations/pingwin/family-categories' => 'restauracao.configurar',
        'POST {id}/integrations/pingwin/family-categories/ai-suggest' => 'restauracao.configurar',
        'GET {id}/integrations/pingwin/heatmap' => 'restauracao.ver',
        'GET {id}/integrations/pingwin/locations' => 'restauracao.ver',
        'POST {id}/integrations/pingwin/locations' => 'restauracao.criar',
        'DELETE {id}/integrations/pingwin/locations/{locationId}' => 'restauracao.apagar',
        'PATCH {id}/integrations/pingwin/locations/{locationId}' => 'restauracao.editar',
        'GET {id}/integrations/pingwin/marketing-data' => 'restauracao.ver',
        'GET {id}/integrations/pingwin/payment-conditions' => 'restauracao.ver',
        'POST {id}/integrations/pingwin/payment-conditions' => 'restauracao.criar',
        'GET {id}/integrations/pingwin/payment-conditions/creation/{creationId}' => 'restauracao.ver',
        'GET {id}/integrations/pingwin/payment-conditions/docs-template' => 'restauracao.ver',
        'POST {id}/integrations/pingwin/payment-conditions/sync' => 'restauracao.editar',
        'DELETE {id}/integrations/pingwin/payment-conditions/{paycondId}' => 'restauracao.apagar',
        'PUT {id}/integrations/pingwin/payment-conditions/{paycondId}' => 'restauracao.editar',
        'GET {id}/integrations/pingwin/supplier-cc' => 'restauracao.ver',
        'GET {id}/integrations/pingwin/supplier-cc/{supplierId}' => 'restauracao.ver',
        'POST {id}/integrations/pingwin/supplier-cc/{supplierId}/refresh' => 'restauracao.editar',
        'GET {id}/integrations/pingwin/supplier-cc/{supplierId}/statement' => 'restauracao.ver',
        'GET {id}/integrations/pingwin/supplier-cc/{supplierId}/status' => 'restauracao.ver',
        'GET {id}/integrations/pingwin/supplier-documents' => 'restauracao.ver',
        'POST {id}/integrations/pingwin/supplier-documents/sync' => 'restauracao.editar',
        'GET {id}/integrations/pingwin/supplier-documents/sync-runs/{runId}' => 'restauracao.ver',
        'GET {id}/integrations/pingwin/suppliers' => 'restauracao.ver',
        'POST {id}/integrations/pingwin/suppliers' => 'restauracao.criar',
        'POST {id}/integrations/pingwin/suppliers/sync' => 'restauracao.editar',
        'GET {id}/integrations/pingwin/suppliers/writes/{writeId}' => 'restauracao.ver',
        'DELETE {id}/integrations/pingwin/suppliers/{supplierId}' => 'restauracao.apagar',
        'PUT {id}/integrations/pingwin/suppliers/{supplierId}' => 'restauracao.editar',
        'POST {id}/integrations/pingwin/sync' => 'restauracao.editar',
        'POST {id}/integrations/pingwin/sync-queue' => 'restauracao.editar',
        'GET {id}/integrations/pingwin/units' => 'restauracao.ver',
        'POST {id}/integrations/pingwin/units/create' => 'restauracao.criar',
        'GET {id}/integrations/pingwin/units/creations/{creationId}' => 'restauracao.ver',
        'POST {id}/integrations/pingwin/units/sync' => 'restauracao.editar',
        'POST {id}/integrations/pingwin/units/{unitId}/anular' => 'restauracao.apagar',
        'POST {id}/integrations/pingwin/units/{unitId}/edit' => 'restauracao.editar',
        'GET {id}/integrations/pingwin/units/{unitId}/usage' => 'restauracao.ver',
        'POST {id}/integrations/restaurant/sync-period' => 'restauracao.criar',
        'GET {id}/ocr/articles/form' => 'restauracao.ver',
        'GET {id}/ocr/articles/search' => 'restauracao.ver',
        'GET {id}/ocr/invoices' => 'restauracao.ver',
        'POST {id}/ocr/invoices' => 'restauracao.criar',
        'GET {id}/ocr/invoices/{invoiceId}' => 'restauracao.ver',
        'PUT {id}/ocr/invoices/{invoiceId}' => 'restauracao.editar',
        'GET {id}/ocr/invoices/{invoiceId}/image' => 'restauracao.ver',
        'POST {id}/ocr/invoices/{invoiceId}/lines/accept-suggestions' => 'restauracao.editar',
        'POST {id}/ocr/invoices/{invoiceId}/lines/relink' => 'restauracao.editar',
        'DELETE {id}/ocr/invoices/{invoiceId}/lines/{lineId}/article' => 'restauracao.apagar',
        'POST {id}/ocr/invoices/{invoiceId}/lines/{lineId}/article' => 'restauracao.criar',
        'POST {id}/ocr/invoices/{invoiceId}/lines/{lineId}/create-article' => 'restauracao.criar',
        'POST {id}/ocr/invoices/{invoiceId}/lines/{lineId}/launch-unit' => 'restauracao.editar',
        'GET {id}/ocr/invoices/{invoiceId}/pingwin-launch' => 'restauracao.ver',
        'POST {id}/ocr/invoices/{invoiceId}/pingwin-launch' => 'restauracao.criar',
        'POST {id}/ocr/invoices/{invoiceId}/pingwin-launch/close' => 'restauracao.editar',
        'POST {id}/ocr/invoices/{invoiceId}/pingwin-launch/void' => 'restauracao.apagar',
        'DELETE {id}/ocr/invoices/{invoiceId}/pingwin-link' => 'restauracao.apagar',
        'POST {id}/ocr/invoices/{invoiceId}/pingwin-link' => 'restauracao.criar',
        'POST {id}/ocr/invoices/{invoiceId}/pingwin-link/confirm' => 'restauracao.editar',
        'POST {id}/ocr/invoices/{invoiceId}/reprocess' => 'restauracao.editar',
        // ── automovel ──
        'GET {id}/automotive-hub' => 'automovel.ver',
        'GET {id}/automotive-hub/funnel' => 'automovel.ver',
        'PUT {id}/car-ai-analyses-feedback/{carAiAnalysesId}' => 'automovel.editar',
        'POST {id}/car-ai-analyses/{carId}' => 'automovel.criar',
        'POST {id}/carmine-connection/sync' => 'automovel.editar',
        'GET {id}/cars' => 'automovel.ver',
        'POST {id}/cars' => 'automovel.criar',
        'POST {id}/cars/generate-description' => 'automovel.criar',
        'GET {id}/cars/promotion-ranking' => 'automovel.ver',
        'GET {id}/cars/{carId}/ad-campaigns' => 'automovel.ver',
        'POST {id}/cars/{carId}/ad-campaigns' => 'automovel.criar',
        'GET {id}/cars/{carId}/ad-campaigns/active-targets' => 'automovel.ver',
        'DELETE {id}/cars/{carId}/ad-campaigns/{campaign}' => 'automovel.apagar',
        'PATCH {id}/cars/{carId}/ad-campaigns/{campaign}/toggle' => 'automovel.editar',
        'POST {id}/cars/{carId}/analysis/regenerate' => 'automovel.editar',
        'GET {id}/cars/{carId}/analytics' => 'automovel.ver',
        'GET {id}/cars/{carId}/audience' => 'automovel.ver',
        'GET {id}/cars/{carId}/audience-analysis' => 'automovel.ver',
        'GET {id}/cars/{carId}/decision' => 'automovel.ver',
        'POST {id}/cars/{carId}/document-templates/{templateId}/generate' => 'automovel.editar',
        'POST {id}/cars/{carId}/execute-action' => 'automovel.editar',
        'GET {id}/cars/{carId}/images/download' => 'automovel.ver',
        'POST {id}/cars/{carId}/images/{imageId}/recrop' => 'automovel.editar',
        'GET {id}/cars/{carId}/margin' => 'automovel.ver',
        'GET {id}/cars/{carId}/market-aggregate' => 'automovel.ver',
        'GET {id}/cars/{carId}/market-aggregate/check-link' => 'automovel.ver',
        'POST {id}/cars/{carId}/market-aggregate/refresh' => 'automovel.editar',
        'POST {id}/cars/{carId}/meta-ads/refresh' => 'automovel.editar',
        'GET {id}/cars/{carId}/print-sheet' => 'automovel.ver',
        'GET {id}/cars/{carId}/sale-document-data' => 'automovel.ver',
        'POST {id}/cars/{carId}/satisfaction-report' => 'automovel.criar',
        'POST {id}/cars/{carId}/satisfaction-report/mark-sent' => 'automovel.editar',
        'GET {id}/cars/{carId}/satisfaction-report/photos' => 'automovel.ver',
        'GET {id}/cars/{carId}/satisfaction-report/review' => 'automovel.ver',
        'POST {id}/cars/{carId}/satisfaction-report/send-email' => 'automovel.editar',
        'GET {id}/cars/{carId}/specs' => 'automovel.ver',
        'DELETE {id}/cars/{car}' => 'automovel.apagar',
        'GET {id}/cars/{car}' => 'automovel.ver',
        'PUT {id}/cars/{car}' => 'automovel.editar',
        'GET {id}/cars/{car}/performance' => 'automovel.ver',
        'POST {id}/cars/{car}/performance' => 'automovel.criar',
        'GET {id}/cars/{car}/performance/summary' => 'automovel.ver',
        'PUT {id}/cars/{car}/performance/{metric}' => 'automovel.editar',
        'GET {id}/cars/{car}/potential-score' => 'automovel.ver',
        'POST {id}/cars/{car}/potential-score/recalculate' => 'automovel.editar',
        'PATCH {id}/cars/{car}/sale' => 'automovel.editar',
        'GET {id}/cars/{car}/sale/lead-match' => 'automovel.ver',
        'POST {id}/cars/{car}/sale/link-lead' => 'automovel.editar',
        'POST {id}/cars/{car}/sales' => 'automovel.criar',
        'GET {id}/dashboard' => 'automovel.ver',
        'GET {id}/dashboard/sales-revenue' => 'automovel.ver',
        'GET {id}/dashboard/stock-breakdown' => 'automovel.ver',
        'GET {id}/decisions' => 'automovel.ver',
        'GET {id}/document-templates' => 'automovel.ver',
        'POST {id}/document-templates' => 'automovel.criar',
        'GET {id}/document-templates/example' => 'automovel.ver',
        'GET {id}/document-templates/variables' => 'automovel.ver',
        'DELETE {id}/document-templates/{template}' => 'automovel.apagar',
        'PUT {id}/document-templates/{template}' => 'automovel.editar',
        'POST {id}/document-templates/{template}/replace' => 'automovel.editar',
        'GET {id}/leads' => 'automovel.ver',
        'PUT {id}/leads/{lead}' => 'automovel.editar',
        'GET {id}/scraper/executions' => 'automovel.ver',
        'GET {id}/scraper/executions/{runId}' => 'automovel.ver',
        'POST {id}/scraper/run' => 'automovel.editar',
        'GET {id}/stock/promotion-candidates' => 'automovel.ver',
        'GET {id}/stock/promotion-candidates/summary' => 'automovel.ver',
        'DELETE {id}/stock/promotion-candidates/{carId}' => 'automovel.apagar',
        'POST {id}/stock/promotion-candidates/{carId}' => 'automovel.criar',
        // ── suporte ──
        'GET {id}/quotes' => 'suporte.ver',
        'GET {id}/quotes/{quote}/pdf' => 'suporte.ver',
        'GET {id}/support-tickets' => 'suporte.ver',
        'POST {id}/support-tickets' => 'suporte.criar',
        'GET {id}/support-tickets/quotes' => 'suporte.ver',
        'GET {id}/support-tickets/{ticket}' => 'suporte.ver',
        'POST {id}/support-tickets/{ticket}/messages' => 'suporte.criar',
        'GET {id}/tasks' => 'suporte.ver',
        'POST {id}/tasks' => 'suporte.criar',
        'DELETE {id}/tasks/{task}' => 'suporte.apagar',
        'PUT {id}/tasks/{task}' => 'suporte.editar',
        'PATCH {id}/tasks/{task}/move' => 'suporte.editar',
        // ── agencia ──
        'POST {id}/management/first-admin' => 'agencia.configurar',
        // ── plataforma ──
        'DELETE {company}' => 'plataforma.configurar',
        'PUT {id}/integrations/pingwin/annual-locals' => 'plataforma.configurar',
    ];

    /**
     * Rotas SENSÍVEIS sem o middleware block_when_impersonating, em que o próprio código já
     * recusa durante a impersonation (regra transversal, fora dos perfis). As que têm o
     * middleware são sensíveis por isso.
     */
    public const SENSITIVE = [
        'GET {id}/integrations/meta/oauth-url',
        'GET {id}/management/requests',
        'POST {id}/integrations/pingwin/excluded-items/{itemId}/include',
        'POST {id}/integrations/pingwin/family-categories/ai-suggest',
        'PUT {id}/integrations/pingwin/family-categories',
    ];

    /**
     * D8: módulos verificados no backend nas rotas que hoje só o menu escondia (os 9 de
     * restauracao_*, marketing_analytics e support_tasks). Só as rotas EXCLUSIVAS de cada
     * módulo: as partilhadas com páginas de outros módulos (por exemplo, a lista dos
     * fornecedores do PingWin, usada nos artigos e nos fornecedores) ficam só com o módulo
     * principal. Somam-se aos ensure_module da própria rota.
     */
    public const MODULES = [
        'GET {id}/integrations/pingwin/locations' => 'restauracao_lojas',
        'POST {id}/integrations/pingwin/locations' => 'restauracao_lojas',
        'PATCH {id}/integrations/pingwin/locations/{locationId}' => 'restauracao_lojas',
        'DELETE {id}/integrations/pingwin/locations/{locationId}' => 'restauracao_lojas',
        'POST {id}/integrations/covermanager/sync' => 'restauracao_lojas',
        'POST {id}/integrations/restaurant/sync-period' => 'restauracao_lojas',
        'GET {id}/analytics/pingwin/calendar' => 'restauracao_calendario',
        'GET {id}/integrations/pingwin/documents' => 'restauracao_documentos',
        'POST {id}/integrations/pingwin/documents/sync' => 'restauracao_documentos',
        'POST {id}/integrations/pingwin/documents/sync-rich' => 'restauracao_documentos',
        'POST {id}/integrations/pingwin/documents' => 'restauracao_documentos',
        'GET {id}/integrations/pingwin/documents/writes/{writeId}' => 'restauracao_documentos',
        'PUT {id}/integrations/pingwin/documents/{externalId}' => 'restauracao_documentos',
        'DELETE {id}/integrations/pingwin/documents/{externalId}' => 'restauracao_documentos',
        'GET {id}/integrations/pingwin/documents/{externalId}' => 'restauracao_documentos',
        'GET {id}/integrations/pingwin/catalog' => 'restauracao_artigos',
        'POST {id}/integrations/pingwin/catalog/sync' => 'restauracao_artigos',
        'GET {id}/integrations/pingwin/articles/form-lookups' => 'restauracao_artigos',
        'GET {id}/integrations/pingwin/articles/{productId}' => 'restauracao_artigos',
        'GET {id}/integrations/pingwin/articles/read/{token}' => 'restauracao_artigos',
        'GET {id}/integrations/pingwin/articles/{catalogItemId}/supplier-prices' => 'restauracao_artigos',
        'POST {id}/integrations/pingwin/articles' => 'restauracao_artigos',
        'GET {id}/integrations/pingwin/articles/creation/{creationId}' => 'restauracao_artigos',
        'PUT {id}/integrations/pingwin/articles/{catalogItemId}' => 'restauracao_artigos',
        'GET {id}/integrations/pingwin/articles/edition/{creationId}' => 'restauracao_artigos',
        'DELETE {id}/integrations/pingwin/articles/{catalogItemId}' => 'restauracao_artigos',
        'GET {id}/integrations/pingwin/articles/deletion/{creationId}' => 'restauracao_artigos',
        'GET {id}/integrations/pingwin/families' => 'restauracao_familias',
        'POST {id}/integrations/pingwin/families/sync' => 'restauracao_familias',
        'POST {id}/integrations/pingwin/suppliers/sync' => 'restauracao_fornecedores',
        'GET {id}/ocr/invoices' => 'restauracao_faturas',
        'POST {id}/ocr/invoices' => 'restauracao_faturas',
        'GET {id}/ocr/invoices/{invoiceId}' => 'restauracao_faturas',
        'GET {id}/ocr/invoices/{invoiceId}/image' => 'restauracao_faturas',
        'PUT {id}/ocr/invoices/{invoiceId}' => 'restauracao_faturas',
        'POST {id}/ocr/invoices/{invoiceId}/reprocess' => 'restauracao_faturas',
        'POST {id}/ocr/invoices/{invoiceId}/pingwin-link' => 'restauracao_faturas',
        'POST {id}/ocr/invoices/{invoiceId}/pingwin-link/confirm' => 'restauracao_faturas',
        'DELETE {id}/ocr/invoices/{invoiceId}/pingwin-link' => 'restauracao_faturas',
        'GET {id}/ocr/articles/search' => 'restauracao_faturas',
        'GET {id}/ocr/articles/form' => 'restauracao_faturas',
        'POST {id}/ocr/invoices/{invoiceId}/lines/accept-suggestions' => 'restauracao_faturas',
        'POST {id}/ocr/invoices/{invoiceId}/lines/relink' => 'restauracao_faturas',
        'POST {id}/ocr/invoices/{invoiceId}/lines/{lineId}/article' => 'restauracao_faturas',
        'DELETE {id}/ocr/invoices/{invoiceId}/lines/{lineId}/article' => 'restauracao_faturas',
        'POST {id}/ocr/invoices/{invoiceId}/lines/{lineId}/create-article' => 'restauracao_faturas',
        'GET {id}/ocr/invoices/{invoiceId}/pingwin-launch' => 'restauracao_faturas',
        'POST {id}/ocr/invoices/{invoiceId}/pingwin-launch' => 'restauracao_faturas',
        'POST {id}/ocr/invoices/{invoiceId}/pingwin-launch/close' => 'restauracao_faturas',
        'POST {id}/ocr/invoices/{invoiceId}/pingwin-launch/void' => 'restauracao_faturas',
        'POST {id}/ocr/invoices/{invoiceId}/lines/{lineId}/launch-unit' => 'restauracao_faturas',
        'GET {id}/integrations/pingwin/supplier-documents' => 'restauracao_faturas',
        'POST {id}/integrations/pingwin/supplier-documents/sync' => 'restauracao_faturas',
        'GET {id}/integrations/pingwin/supplier-documents/sync-runs/{runId}' => 'restauracao_faturas',
        'GET {id}/integrations/pingwin/units' => 'restauracao_unidades',
        'POST {id}/integrations/pingwin/units/sync' => 'restauracao_unidades',
        'POST {id}/integrations/pingwin/units/create' => 'restauracao_unidades',
        'GET {id}/integrations/pingwin/units/creations/{creationId}' => 'restauracao_unidades',
        'GET {id}/integrations/pingwin/units/{unitId}/usage' => 'restauracao_unidades',
        'POST {id}/integrations/pingwin/units/{unitId}/edit' => 'restauracao_unidades',
        'POST {id}/integrations/pingwin/units/{unitId}/anular' => 'restauracao_unidades',
        'POST {id}/integrations/pingwin/payment-conditions/sync' => 'restauracao_condicoes_pagamento',
        'GET {id}/integrations/pingwin/payment-conditions/docs-template' => 'restauracao_condicoes_pagamento',
        'GET {id}/integrations/pingwin/payment-conditions/creation/{creationId}' => 'restauracao_condicoes_pagamento',
        'POST {id}/integrations/pingwin/payment-conditions' => 'restauracao_condicoes_pagamento',
        'PUT {id}/integrations/pingwin/payment-conditions/{paycondId}' => 'restauracao_condicoes_pagamento',
        'DELETE {id}/integrations/pingwin/payment-conditions/{paycondId}' => 'restauracao_condicoes_pagamento',
        'GET {id}/analytics/meta/overview' => 'marketing_analytics',
        'GET {id}/analytics/meta/ad-tag-warnings' => 'marketing_analytics',
        'GET {id}/support-tickets' => 'support_tasks',
        'POST {id}/support-tickets' => 'support_tasks',
        'GET {id}/support-tickets/quotes' => 'support_tasks',
        'POST {id}/support-tickets/quotes/approve' => 'support_tasks',
        'GET {id}/support-tickets/{ticket}' => 'support_tasks',
        'POST {id}/support-tickets/{ticket}/messages' => 'support_tasks',
        'PATCH {id}/support-tickets/{ticket}/quote-decision' => 'support_tasks',
        'GET {id}/tasks' => 'support_tasks',
        'POST {id}/tasks' => 'support_tasks',
        'PUT {id}/tasks/{task}' => 'support_tasks',
        'PATCH {id}/tasks/{task}/move' => 'support_tasks',
        'DELETE {id}/tasks/{task}' => 'support_tasks',
    ];

    /** Rotas sobre a PRÓPRIA conta: a pessoa pode sempre ver e alterar a sua (rota → parâmetro do utilizador). */
    public const SELF = [
        'GET {id}/users/{user}' => 'user',
        'PUT {id}/users/{user}' => 'user',
    ];

    /** "GET {id}/blogs" para a rota dada (null se não for uma rota de empresa). */
    public static function keyFor(Route $route): ?string
    {
        $uri = $route->uri();
        if (! str_starts_with($uri, self::PREFIX) || ! preg_match('#^api/v1/companies/\{(id|company)\}#', $uri)) {
            return null;
        }
        $method = collect($route->methods())->reject(fn ($m) => $m === 'HEAD')->first();

        return $method . ' ' . substr($uri, strlen(self::PREFIX));
    }

    public static function permissionFor(Route $route): ?string
    {
        $key = self::keyFor($route);

        return $key === null ? null : (self::MAP[$key] ?? null);
    }
}
